name: Build Electron Forge

on:
  push:
    branches:
    # this will run on the electron branch
      - main

jobs:

  build:
    name: Build Electron Forge
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

      - uses: actions/checkout@main

      - name: Setup NodeJs
        uses: actions/setup-node@main
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm run install

      - name: Build
        run: npm run package

      - name: Upload builds to release
        uses: softprops/action-gh-release@main
        with:
          tag_name: ${{ github.ref }}
          files: out/*.*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Nightly Build
        uses: actions/upload-artifact@main
        if: success()
        with:
          name: Electron Forge-nightly
          path: out/**/*!(.zip)
