name: Build Electron Forge

on:
  workflow_dispatch:

jobs:

  build:
    name: Build Electron Forge
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: Clone main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: ./desktop
        run: npm install

      - name: Build
        working-directory: ./desktop
        run: npm run make

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: "Build for ${{ matrix.os }} - version ${{ matrix.version }}"
      #     path: desktop/out/
