name: Build Electron Forge

on:
  push:
    branches:
    # this will run on the electron branch
      - main

jobs:

  build:
    name: Build Electron Forge
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Clone main
        uses: actions/checkout@main

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: ./desktop
        run: npm install

      - name: Build
        working-directory: ./desktop
        run: npm run make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Build for ${{ matrix.os }} - version ${{ matrix.version }}"
          path: desktop/out/

      # - name: Upload builds to release
      #   uses: softprops/action-gh-release@main
      #   with:
      #     tag_name: ${{ github.ref }}
      #     files: out/*.*
      #     draft: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Nightly Build
      #   uses: actions/upload-artifact@main
      #   if: success()
      #   with:
      #     name: Electron Forge-nightly
      #     path: out/**/*!(.zip)

      - name: Release
        if: matrix.os == 'ubuntu-latest'
        run: npx semantic-release
