name: "Release Changelog"
on:
  push:
    tags:
      - "v*"

jobs:
  build-changelog:
    name: "Build Changelog"
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}